### ISSUE TITLE
More related projects

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/safeframe#52]
I haven't taken a deep-dive on this package, but does [{struct}](https://github.com/cynkra/struct) have a similar role to {safeframe}?

Is it also worth documenting somewhere the differences, pros and cons of {safeframe} versus S4 classes (in the {methods} package that is part of R) in R? S4 is much broader in scope but object invalidation is likely one of the key reasons someone would use either.

**Comment by chartgerink** [comment]
Thanks! It looks relevant enough to add it 😊 Will do so now 👍
